from enum import StrEnum


class Classification(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class ProjectState(StrEnum):
    DRAFT = "DRAFT"
    DISCOVERY_PLANNED = "DISCOVERY_PLANNED"
    DISCOVERY_ACTIVE = "DISCOVERY_ACTIVE"
    ANALYSIS_ACTIVE = "ANALYSIS_ACTIVE"
    VALIDATION_ACTIVE = "VALIDATION_ACTIVE"
    BASELINED = "BASELINED"
    DELIVERY_SUPPORT = "DELIVERY_SUPPORT"
    ON_HOLD = "ON_HOLD"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class EpistemicStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    INFERRED = "INFERRED"
    ASSUMED = "ASSUMED"
    DISPUTED = "DISPUTED"
    UNKNOWN = "UNKNOWN"


class LifecycleStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class RequirementState(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    BASELINED = "BASELINED"
    IMPLEMENTING = "IMPLEMENTING"
    VERIFIED = "VERIFIED"
    DELIVERED = "DELIVERED"
    DEFERRED = "DEFERRED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class RiskState(StrEnum):
    PROPOSED = "PROPOSED"
    OPEN = "OPEN"
    TREATING = "TREATING"
    MONITORING = "MONITORING"
    ACCEPTED = "ACCEPTED"
    CLOSED = "CLOSED"
    MATERIALISED = "MATERIALISED"


class DecisionState(StrEnum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"
    SUPERSEDED = "SUPERSEDED"


class ReviewTaskState(StrEnum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    WAIVED = "WAIVED"
    CANCELLED = "CANCELLED"


class GateResult(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    PASS = "PASS"
    PASS_WITH_WAIVERS = "PASS_WITH_WAIVERS"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"


class DocumentProcessingState(StrEnum):
    UPLOADED = "UPLOADED"
    SCANNING = "SCANNING"
    PARSING = "PARSING"
    CLASSIFYING = "CLASSIFYING"
    CHUNKING = "CHUNKING"
    EMBEDDING = "EMBEDDING"
    INDEXING = "INDEXING"
    EXTRACTING = "EXTRACTING"
    READY = "READY"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    DELETED = "DELETED"


class AITaskState(StrEnum):
    QUEUED = "QUEUED"
    CONTEXT_BUILDING = "CONTEXT_BUILDING"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ArtefactState(StrEnum):
    DRAFT = "DRAFT"
    RENDERING = "RENDERING"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class ChangeRequestState(StrEnum):
    DRAFT = "DRAFT"
    TRIAGE = "TRIAGE"
    IMPACT_ANALYSIS = "IMPACT_ANALYSIS"
    ESTIMATING = "ESTIMATING"
    DECISION_PENDING = "DECISION_PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"
    IMPLEMENTING = "IMPLEMENTING"
    CLOSED = "CLOSED"


APPENDIX_A_STATE_ENUMS = (
    ProjectState,
    EpistemicStatus,
    LifecycleStatus,
    RequirementState,
    RiskState,
    DecisionState,
    ReviewTaskState,
    GateResult,
    DocumentProcessingState,
    AITaskState,
    ArtefactState,
    ChangeRequestState,
)

